-- ============================================================
-- Lookup Tables: h_phrase, p_phrase
-- ============================================================

CREATE TABLE IF NOT EXISTS eforsch.h_phrase (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phrase_code VARCHAR(20) NOT NULL UNIQUE,
    phrase_description VARCHAR(500) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eforsch.p_phrase (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phrase_code VARCHAR(20) NOT NULL UNIQUE,
    phrase_description VARCHAR(500) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eforsch.company (
    id           INT PRIMARY KEY AUTO_INCREMENT,
    company_no   VARCHAR(20)  NOT NULL,
    company_name VARCHAR(255) NOT NULL
);

-- Create index on company_no for faster queries (since multiple companies can have same company_no)
CREATE INDEX idx_company_no ON eforsch.company(company_no);

-- Sample H-Phrases (Hazard Statements)
INSERT IGNORE INTO eforsch.h_phrase (phrase_code, phrase_description) VALUES
('H200', 'Unstable explosive'),
('H201', 'Explosive; mass explosion hazard'),
('H202', 'Explosive; severe projection hazard'),
('H203', 'Explosive; fire, blast or projection hazard'),
('H204', 'Fire or projection hazard'),
('H220', 'Extremely flammable gas'),
('H221', 'Flammable gas'),
('H222', 'Extremely flammable aerosol'),
('H223', 'Flammable aerosol'),
('H224', 'Extremely flammable liquid and vapour'),
('H225', 'Highly flammable liquid and vapour'),
('H226', 'Flammable liquid and vapour'),
('H228', 'Flammable solid'),
('H240', 'Heating may cause an explosion'),
('H241', 'Heating may cause a fire or explosion'),
('H242', 'Heating may cause a fire'),
('H250', 'Catches fire spontaneously if exposed to air'),
('H251', 'Self-heating; may catch fire'),
('H252', 'Self-heating in large quantities; may catch fire'),
('H260', 'In contact with water releases flammable gases which may ignite spontaneously'),
('H261', 'In contact with water releases flammable gas'),
('H270', 'May cause or intensify fire; oxidiser'),
('H271', 'May cause fire or explosion; strong oxidiser'),
('H272', 'May intensify fire; oxidiser'),
('H280', 'Contains gas under pressure; may explode if heated'),
('H281', 'Contains refrigerated gas; may cause cryogenic burns or injury'),
('H290', 'May be corrosive to metals'),
('H300', 'Fatal if swallowed'),
('H301', 'Toxic if swallowed'),
('H302', 'Harmful if swallowed'),
('H304', 'May be fatal if swallowed and enters airways'),
('H310', 'Fatal in contact with skin'),
('H311', 'Toxic in contact with skin'),
('H312', 'Harmful in contact with skin'),
('H314', 'Causes severe skin burns and eye damage'),
('H315', 'Causes skin irritation'),
('H317', 'May cause an allergic skin reaction'),
('H318', 'Causes serious eye damage'),
('H319', 'Causes serious eye irritation'),
('H330', 'Fatal if inhaled'),
('H331', 'Toxic if inhaled'),
('H332', 'Harmful if inhaled'),
('H334', 'May cause allergy or asthma symptoms or breathing difficulties if inhaled'),
('H335', 'May cause respiratory irritation'),
('H336', 'May cause drowsiness or dizziness'),
('H340', 'May cause genetic defects'),
('H341', 'Suspected of causing genetic defects'),
('H350', 'May cause cancer'),
('H351', 'Suspected of causing cancer'),
('H360', 'May damage fertility or the unborn child'),
('H361', 'Suspected of damaging fertility or the unborn child'),
('H362', 'May cause harm to breast-fed children'),
('H370', 'Causes damage to organs'),
('H371', 'May cause damage to organs'),
('H372', 'Causes damage to organs through prolonged or repeated exposure'),
('H373', 'May cause damage to organs through prolonged or repeated exposure'),
('H400', 'Very toxic to aquatic life'),
('H401', 'Toxic to aquatic life'),
('H402', 'Harmful to aquatic life'),
('H410', 'Very toxic to aquatic life with long lasting effects'),
('H411', 'Toxic to aquatic life with long lasting effects'),
('H412', 'Harmful to aquatic life with long lasting effects'),
('H413', 'May cause long lasting harmful effects to aquatic life'),
('H420', 'Harms public health and the environment by destroying ozone in the upper atmosphere');

-- Sample P-Phrases (Precautionary Statements)
INSERT IGNORE INTO eforsch.p_phrase (phrase_code, phrase_description) VALUES
('P101', 'If medical advice is needed, have product container or label at hand'),
('P102', 'Keep out of reach of children'),
('P103', 'Read label before use'),
('P201', 'Obtain special instructions before use'),
('P202', 'Do not handle until all safety precautions have been read and understood'),
('P210', 'Keep away from heat, hot surfaces, sparks, open flames and other ignition sources. No smoking'),
('P211', 'Do not spray on an open flame or other ignition source'),
('P220', 'Keep away from clothing and other combustible materials'),
('P221', 'Take precautionary measures against mixing with combustibles'),
('P222', 'Do not allow contact with air'),
('P223', 'Do not allow contact with water'),
('P230', 'Keep wetted with...'),
('P231', 'Handle under inert gas'),
('P232', 'Protect from moisture'),
('P233', 'Keep container tightly closed'),
('P234', 'Keep only in original container'),
('P235', 'Keep cool'),
('P240', 'Ground and bond container and receiving equipment'),
('P241', 'Use explosion-proof electrical/ventilating/lighting equipment'),
('P242', 'Use only non-sparking tools'),
('P243', 'Take precautionary measures against static discharge'),
('P244', 'Keep valves and fittings free from oil and grease'),
('P250', 'Do not subject to grinding/shock/friction'),
('P251', 'Do not pierce or burn, even after use'),
('P260', 'Do not breathe dust/fume/gas/mist/vapours/spray'),
('P261', 'Avoid breathing dust/fume/gas/mist/vapours/spray'),
('P262', 'Do not get in eyes, on skin, or on clothing'),
('P263', 'Avoid contact during pregnancy and while nursing'),
('P264', 'Wash hands thoroughly after handling'),
('P270', 'Do not eat, drink or smoke when using this product'),
('P271', 'Use only outdoors or in a well-ventilated area'),
('P272', 'Contaminated work clothing should not be allowed out of the workplace'),
('P273', 'Avoid release to the environment'),
('P280', 'Wear protective gloves/protective clothing/eye protection/face protection'),
('P281', 'Use personal protective equipment as required'),
('P282', 'Wear cold insulating gloves and either face shield or eye protection'),
('P283', 'Wear fire resistant/flame retardant clothing'),
('P284', 'In case of inadequate ventilation wear respiratory protection'),
('P285', 'In case of inadequate ventilation wear respiratory protection'),
('P301', 'IF SWALLOWED'),
('P302', 'IF ON SKIN'),
('P303', 'IF ON SKIN OR HAIR'),
('P304', 'IF INHALED'),
('P305', 'IF IN EYES'),
('P306', 'IF ON CLOTHING'),
('P307', 'IF exposed'),
('P308', 'IF exposed or concerned'),
('P310', 'Immediately call a POISON CENTER or doctor/physician'),
('P311', 'Call a POISON CENTER or doctor/physician'),
('P312', 'Call a POISON CENTER or doctor/physician if you feel unwell'),
('P313', 'Get medical advice/attention'),
('P314', 'Get medical advice/attention if you feel unwell'),
('P315', 'Get immediate medical advice/attention'),
('P320', 'Specific treatment is urgent'),
('P321', 'Specific treatment'),
('P322', 'Specific measures'),
('P330', 'Rinse mouth'),
('P331', 'Do NOT induce vomiting'),
('P332', 'If skin irritation occurs: Get medical advice/attention'),
('P333', 'If skin irritation or rash occurs: Get medical advice/attention'),
('P334', 'Immerse in cool water or wrap in wet bandages'),
('P335', 'Brush off loose particles from skin'),
('P336', 'Thaw frosted parts with lukewarm water. Do not rub affected area'),
('P337', 'If eye irritation persists: Get medical advice/attention'),
('P338', 'Remove contact lenses, if present and easy to do. Continue rinsing'),
('P340', 'Remove victim to fresh air and keep at rest in a position comfortable for breathing'),
('P341', 'If breathing is difficult, remove victim to fresh air and keep at rest in a position comfortable for breathing'),
('P342', 'If experiencing respiratory symptoms: Call a POISON CENTER or doctor/physician'),
('P350', 'Gently wash with plenty of soap and water'),
('P351', 'Rinse cautiously with water for several minutes'),
('P352', 'Wash with plenty of soap and water'),
('P353', 'Rinse skin with water/shower'),
('P360', 'Rinse immediately contaminated clothing and skin with plenty of water before removing clothes'),
('P361', 'Remove/Take off immediately all contaminated clothing'),
('P362', 'Take off contaminated clothing and wash before reuse'),
('P363', 'Wash contaminated clothing before reuse'),
('P370', 'In case of fire'),
('P371', 'In case of major fire and large quantities'),
('P372', 'Explosion risk in case of fire'),
('P373', 'DO NOT fight fire when fire reaches explosives'),
('P374', 'Fight fire with normal precautions from a reasonable distance'),
('P375', 'Fight fire remotely due to the risk of explosion'),
('P376', 'Stop leak if safe to do so'),
('P377', 'Leaking gas fire: Do not extinguish, unless leak can be stopped safely'),
('P378', 'Use appropriate media for extinction'),
('P380', 'Evacuate area'),
('P381', 'In case of leakage, eliminate all ignition sources'),
('P390', 'Absorb spillage to prevent material damage'),
('P391', 'Collect spillage'),
('P401', 'Store in accordance with...'),
('P402', 'Store in a dry place'),
('P403', 'Store in a well-ventilated place'),
('P404', 'Store in a closed container'),
('P405', 'Store locked up'),
('P406', 'Store in corrosive resistant container with a resistant inner liner'),
('P407', 'Maintain air gap between stacks/pallets'),
('P410', 'Protect from sunlight'),
('P411', 'Store at temperatures not exceeding ... °C/...°F'),
('P412', 'Do not expose to temperatures exceeding 50°C/122°F'),
('P413', 'Store bulk masses greater than ... kg/...lbs at temperatures not exceeding ...°C/...°F'),
('P420', 'Store separately'),
('P422', 'Store contents under...'),
('P501', 'Dispose of contents/container in accordance with local regulations'),
('P502', 'Refer to manufacturer/supplier for information on recovery/recycling');

INSERT IGNORE INTO eforsch.company (company_no, company_name) VALUES
('700597', 'Carl Roth'),
('716084', 'Fisher Scientific GmbH'),
('717630', 'Jena Biosciences'),
('717630', '10x Genomics, Inc.'),
('714169', 'Abcam'),
('730615', 'Abclonal'),
('730615', 'Abnova'),
('715344', 'Active Motif'),
('715344', 'Addgene'),
('715344', 'Adooq BioScience'),
('700083', 'Agilent Technologies'),
('707968', 'Amazon'),
('703039', 'Applichem'),
('703039', 'ATCC'),
('700034', 'BD Biosciences'),
('700034', 'Beckman Coulter GmbH'),
('700034', 'BioCat'),
('725763', 'Biolegend'),
('703393', 'Biomol GmbH'),
('700390', 'Biorad'),
('704389', 'Bio-Techne GmbH (R&D Systems)'),
('704389', 'Biozol'),
('708365', 'Biozym Scientific GmbH'),
('728582', 'Capricorn Scientific'),
('700597', 'Carl Roth GmbH'),
('722225', 'Cell Signaling Technology'),
('718296', 'Diagenode'),
('713931', 'Engelbert - Strauss'),
('716084', 'Fisher Scientific GmbH'),
('716084', 'GeneScript'),
('700643', 'Greiner Bio One'),
('734182', 'Häberle Labortechnik GmbH & Co KG'),
('734182', 'Hamilton Germany GmbH'),
('708660', 'Haworth'),
('705036', 'HiSS Diagnostics'),
('704538', 'Hölzel Biotech'),
('720527', 'Horizon Discovery Biosciences'),
('720527', 'ibidi'),
('720527', 'IDT'),
('720878', 'Illumina GmbH'),
('720878', 'Integra'),
('717630', 'Jena Bioscience'),
('726451', 'König+Neurath'),
('700220', 'Kraiss & Friz'),
('703609', 'Kroschke sign-international'),
('714867', 'Lonza Verviers SPRL'),
('714867', 'Lyreco'),
('700210', 'Macherey-Nagel'),
('727913', 'MedChemExpress'),
('700039', 'Merck'),
('700642', 'Mettler Toledo GmbH'),
('700642', 'Microsynth Seqlab'),
('702843', 'Miltenyi Biotec GmbH'),
('702843', 'Morphisto'),
('702843', 'NanoLight Technology'),
('710015', 'NEB'),
('710015', 'NovoPro'),
('704389', 'Novus (Bio-Techne GmbH)'),
('705460', 'Panbiotech'),
('705460', 'Pecon'),
('721714', 'PluriSelect'),
('704363', 'Promega'),
('704363', 'Promega GmbH'),
('704363', 'Proteintech'),
('702850', 'QIAGEN GmbH'),
('702850', 'RBK Zentralversorgung'),
('702850', 'Revvity'),
('702850', 'Roscheba'),
('714838', 'Santa Cruz Biotechnology, Inc.'),
('700115', 'Sarstedt'),
('719007', 'Sartorius Stedim Biotech GmbH'),
('719007', 'Science Services'),
('727875', 'Selleck Chemicals GmbH'),
('705008', 'Serva Electrophoresis GmbH'),
('700039', 'SIGMA-ALDRICH Chemie GmbH'),
('727815', 'Sony Europe BV'),
('727815', 'Stiel Kälte + Klima GmbH'),
('714885', 'Takara'),
('714885', 'The Well Bioscience'),
('714885', 'The Leibniz Institute - DSMZ'),
('716084', 'Thermo Fischer Scientific'),
('714399', 'Thermo Fisher/Life Technology'),
('700168', 'Thomas Geyer GmbH & Co. KG'),
('700168', 'Vector Laboratories'),
('705454', 'VWR'),
('705454', 'Warenausgabe RBK'),
('705454', 'Westfalen'),
('710335', 'Wiesinger'),
('710335', 'Wolkdirekt'),
('715743', 'Zymo Research');


-- DDL
CREATE TABLE IF NOT EXISTS eforsch.storage_location (
    id                INT PRIMARY KEY AUTO_INCREMENT,
    storage_location  VARCHAR(255) NOT NULL
);

-- Create index on storage_location for faster queries
CREATE INDEX idx_storage_location ON eforsch.storage_location(storage_location);

-- DML
INSERT IGNORE INTO eforsch.storage_location (storage_location) VALUES
('N.E.110'),
('N.E.110  4 °C'),
('N.E.110  -20 °C'),
('N.E.110  N.E.110_GFS-1_Gefahrstoffe'),
('N.E.110  N.E.110_GFS-2_Gefahrstoffe'),
('N.E.110  N.E.110_GFS-3_Säure-Lauge'),
('N.E.111'),
('N.E.111  4 °C'),
('N.E.120'),
('N.E.120  4 °C'),
('N.E.120  -20 °C'),
('N.E.120  N.E.120_GFS-1_Gefahrstoffe'),
('N.E.120  N.E.120_GFS-2_Gefahrstoffe'),
('N.E.120  N.E.120_GFS-3_Säure-Lauge'),
('N.E.122'),
('N.E.122  4 °C'),
('N.O1.110'),
('N.O1.110  4 °C'),
('N.O1.110  -20 °C'),
('N.O1.110  N.O1.110_GFS-1_Gefahrstoffe'),
('N.O1.110  N.O1.110_GFS-2_Gefahrstoffe'),
('N.O1.110  N.O1.110_GFS-3_Säure-Lauge'),
('N.O1.111'),
('N.O1.111  4 °C'),
('N.O1.120'),
('N.O1.120  4 °C'),
('N.O1.120  -20 °C'),
('N.O1.120  N.O1.120_GFS-1_Gefahrstoffe'),
('N.O1.120  N.O1.120_GFS-2_Gefahrstoffe'),
('N.O1.120  N.O1.120_GFS-3_Säure-Lauge'),
('N.O1.122'),
('N.O1.122  4 °C');

commit;