package com.eforsch.service;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.eforsch.dto.DeleteInventoryRequest;
import com.eforsch.dto.User;
import com.eforsch.entity.ArchiveFineChemicalInventory;
import com.eforsch.entity.ArchiveInventory;
import com.eforsch.entity.FineChemicalInventory;
import com.eforsch.entity.Inventory;
import com.eforsch.repository.ArchiveFineChemicalInventoryRepository;
import com.eforsch.repository.ArchiveInventoryRepository;
import com.eforsch.repository.FineChemicalInventoryRepository;
import com.eforsch.repository.InventoryRepository;
import com.eforsch.util.ArchiveInventoryVO;

@Service
public class ArchiveInventoryService {

	@Autowired private InventoryRepository inventoryRepo;
    @Autowired private FineChemicalInventoryRepository fineChemicalRepo;

    @Autowired private ArchiveInventoryRepository archiveInventoryRepo;
    @Autowired private ArchiveFineChemicalInventoryRepository archiveFineChemicalRepo;

    public Map<String, Object> softDeleteItem(DeleteInventoryRequest request) {
        String type = request.getInventoryType().toLowerCase();
        String group = request.getUser().getGroupName();

		/*
		 * if (!List.of("admin", "labMgmt").contains(role.toLowerCase())) { throw new
		 * RuntimeException("Unauthorized"); }
		 */

        if ("generalInventory".equalsIgnoreCase(type)) {
            Inventory invOpt = inventoryRepo.findByProductId(request.getProduID());
            if (invOpt != null) {
                Inventory inv = (Inventory) invOpt;
               
                // Set properties from Inventory to ArchiveInventory
                ArchiveInventory ar = new ArchiveInventory();
                // archiveId is generated by DB; don't set it.

                setIfNotNull(ar::setProductId, inv.getProductId());
                setIfNotBlank(ar::setProductname, inv.getProductname());
                setIfNotBlank(ar::setCatalogue, inv.getCatalogue());
                setIfNotBlank(ar::setCompanyname, inv.getCompanyname());
                setIfNotNull(ar::setQuantity, inv.getQuantity());
                setIfNotBlank(ar::setGroupName, inv.getGroupName());
                setIfNotBlank(ar::setCompanyinternalno, inv.getCompanyinternalno());
                setIfNotBlank(ar::setSapmaterialno, inv.getSapmaterialno());
                setIfNotBlank(ar::setWeightvolsubqty, inv.getWeightvolsubqty());
                setIfNotBlank(ar::setBudgetno, inv.getBudgetno());
                setIfNotBlank(ar::setConcentration, inv.getConcentration());
                setIfNotBlank(ar::setRemarks, inv.getRemarks());

                setIfNotNull(ar::setOrderdate, inv.getOrderdate());
                setIfNotNull(ar::setExpirydate, inv.getExpirydate());
                setIfNotBlank(ar::setAddedby, inv.getAddedby());

                // shared is primitive in both; copy directly (no null issue)
                ar.setShared(inv.isShared());

                // For price, copy if it’s meaningful (you can change this rule if 0.0 is valid)
                if (inv.getPrice() != 0.0d) {
                    ar.setPrice(inv.getPrice());
                }

                setIfNotBlank(ar::setFileName, inv.getFileName());
                setIfNotBlank(ar::setFileType, inv.getFileType());
                setIfNotEmpty(ar::setFileContent, inv.getFileContent());
               
                ar = archiveInventoryRepo.save(ar);
                
                ArchiveInventoryVO archiveInventoryVO = new ArchiveInventoryVO();
                archiveInventoryVO.setArchiveId(ar.getArchiveId());
                setArchiveVODataFromInventory(archiveInventoryVO, inv);
                inventoryRepo.delete(inv);
                return Map.of("message", "Item soft-deleted and moved to archive", "archivedItem", archiveInventoryVO);
            }
        } else {
            FineChemicalInventory fineOpt = fineChemicalRepo.findByProductId(request.getProduID());
            if (fineOpt != null) {
                FineChemicalInventory src = fineOpt;
                ArchiveFineChemicalInventory dest = new ArchiveFineChemicalInventory();
               
                dest.setProductId(src.getProductId());
                dest.setProductname(src.getProductname());
                dest.setCatalogue(src.getCatalogue());
                dest.setCompanyname(src.getCompanyname());
                dest.setQuantity(src.getQuantity());
                dest.setExpiryDate(src.getExpiryDate());
                dest.setCompanyInternalNo(src.getCompanyInternalNo());
                dest.setSapMaterialNo(src.getSapMaterialNo());
                dest.setWvsubqty(src.getWvsubqty());
                dest.setBudgetno(src.getBudgetno());
                dest.setOrderdate(src.getOrderdate());
                dest.setOrderedby(src.getOrderedby());
                dest.setConcentration(src.getConcentration());
                dest.setAmount(src.getAmount());
                dest.setRemarks(src.getRemarks());
                dest.setCasnumber(src.getCasnumber());
                dest.setHazardousSubstance(src.getHazardousSubstance());
                dest.setCmrSubstance(src.getCmrSubstance());
                dest.setSkinResorptive(src.getSkinResorptive());
                dest.setGhsSymbols(src.getGhsSymbols());
                dest.setGhsSignalWord(src.getGhsSignalWord());
                dest.sethPhrases(src.gethPhrases());
                dest.setpPhrases(src.getpPhrases());
                dest.setSubstitutionCheck(src.getSubstitutionCheck());
                dest.setSubstitutionOption(src.getSubstitutionOption());
                dest.setStorageLocation(src.getStorageLocation());
                dest.setGroupName(src.getGroupName());
                dest.setQtypriceordered(src.getQtypriceordered());
                dest.setPriority(src.getPriority());
                dest.setReceived(src.getReceived());
                dest.setCatalogue(src.getCatalogue());
                dest.setCreatedAt(src.getCreatedAt());
                dest.setPrice(src.getPrice());
                dest.setShared(src.isShared());
                dest.setFileName(src.getFileName());
                dest.setFileType(src.getFileType());
                dest.setFileContent(src.getFileContent());
                dest.setGroupName(group);
                dest = archiveFineChemicalRepo.save(dest);
                
                ArchiveInventoryVO archiveVO = new ArchiveInventoryVO();
                archiveVO.setArchiveId(dest.getArchiveId());
                setArchiveVODataFromInventory(archiveVO, src);                
                fineChemicalRepo.delete(src);
                return Map.of("message", "Item soft-deleted and moved to archive", "archivedItem", archiveVO);
            }
        }

        throw new RuntimeException("Item not found or type invalid");
    }
    
	    private static void setIfNotEmpty(java.util.function.Consumer<byte[]> setter, byte[] value) {
	        if (value != null && value.length > 0) setter.accept(value);
	    }
    
    public Map<String, Object> softDeleteFromArchive(DeleteInventoryRequest request) {
        String type = request.getInventoryType().toLowerCase();
        String role = request.getUser().getRole();
        long userId = request.getUser().getId();

		/*
		 * if (!"LABMGMT".equalsIgnoreCase(role)) { throw new
		 * RuntimeException("Unauthorized. Only Lab Management can perform this action."
		 * ); }
		 */

        if ("generalInventory".equalsIgnoreCase(type)) {
        	Optional<ArchiveInventory> archiveOpt = archiveInventoryRepo.findByProductId(request.getProduID());
            if (archiveOpt.isPresent()) {
                ArchiveInventory archive = archiveOpt.get();
                archive.setVisibleToUsers(false);
                archiveInventoryRepo.save(archive);

                return Map.of(
                    "message", "Archive item soft-deleted (not visible to regular users anymore)",
                    "archiveId", archive.getArchiveId(),
                    "deletedBy", Map.of("userId", userId, "role", role)
                );
            }
        } else {
        	Optional<ArchiveFineChemicalInventory> archiveOpt = archiveFineChemicalRepo.findByProductId(request.getProduID().intValue());
            if (archiveOpt.isPresent()) {
                ArchiveFineChemicalInventory archive = archiveOpt.get();
                archive.setVisibleToUsers(false);
                archiveFineChemicalRepo.save(archive);

                return Map.of(
                    "message", "Archive item soft-deleted (not visible to regular users anymore)",
                    "archiveId", archive.getArchiveId(),
                    "deletedBy", Map.of("userId", userId, "role", role)
                );
            }
        }

        throw new RuntimeException("Archive item not found or invalid type");
    }
    
    public Map<String, Object> permanentDeleteFromArchiveByProductId(DeleteInventoryRequest request) {
        String type = request.getInventoryType().toLowerCase();
        String role = request.getUser().getRole();
        long userId = request.getUser().getId();
        String userRole = role.toLowerCase();
        Date deletionTime = new Date();

		/*
		 * if (!"LABMGMT".equalsIgnoreCase(role)) { throw new
		 * RuntimeException("Unauthorized. Only Lab Management can perform this action."
		 * ); }
		 */

        if ("generalInventory".equalsIgnoreCase(type)) {
            // Search archive by productId
            Optional<ArchiveInventory> archiveOpt = archiveInventoryRepo.findByProductId(request.getProduID());
            if (archiveOpt.isPresent()) {
                ArchiveInventory archive = archiveOpt.get();
                archiveInventoryRepo.deleteById(archive.getArchiveId());
                return Map.of(
                    "message", "Archive item permanently deleted",
                    "archiveId", archive.getArchiveId(),
                    "deletedAt", deletionTime,
                    "deletedBy", Map.of("userId", userId, "role", userRole)
                );
            }
        } else {
            Optional<ArchiveFineChemicalInventory> archiveOpt = archiveFineChemicalRepo.findByProductId(request.getProduID().intValue());
            if (archiveOpt.isPresent()) {
                ArchiveFineChemicalInventory archive = archiveOpt.get();
                archiveFineChemicalRepo.deleteByArchiveId(archive.getArchiveId());
                return Map.of(
                    "message", "Archive item permanently deleted",
                    "archiveId", archive.getArchiveId(),
                    "deletedAt", deletionTime,
                    "deletedBy", Map.of("userId", userId, "role", userRole)
                );
            }
        }

        throw new RuntimeException("Archive item not found for provided product ID and inventory type");
    }
    
    public List<ArchiveInventoryVO> getArchivedItemsByYear() {
     
		/*
		 * if (!"LABMGMT".equalsIgnoreCase(role)) { throw new
		 * RuntimeException("Unauthorized. Only Lab Management can access archive listings."
		 * ); }
		 */
        List<ArchiveInventoryVO> result = new ArrayList<ArchiveInventoryVO>();
        ArchiveInventoryVO archiveEntry = null;
        // --- General Inventory Archive ---
        List<ArchiveInventory> generalList = archiveInventoryRepo.findAll();
        for (ArchiveInventory item : generalList) {
	        	archiveEntry = toVO(item);
	        	archiveEntry.setInventoryType("generalInventory");
	        	result.add(archiveEntry);
        }

        // --- Fine Chemical Archive ---
        List<ArchiveFineChemicalInventory> fineList = archiveFineChemicalRepo.findAll();
        for (ArchiveFineChemicalInventory item : fineList) {
        	archiveEntry = toVO(item);
        	archiveEntry.setInventoryType("fineChemicalInventory");
        	result.add(archiveEntry);
        }

        return result;
    }
    
    public static ArchiveInventoryVO toVO(ArchiveFineChemicalInventory src) {
        if (src == null) return null;

        ArchiveInventoryVO vo = new ArchiveInventoryVO();

        // IDs
        vo.setArchiveId(src.getArchiveId());
        vo.setProductId(src.getProductId());

        // Renamed fields
        setIfNotBlank(vo::setProductName, src.getProductname());
        setIfNotBlank(vo::setCompanyName, src.getCompanyname());

        // Catalogue/catalogue (keep VO.catalogue as provided)
        String cat = firstNonBlank(src.getCatalogue(), src.getCatalogue());
        setIfNotBlank(vo::setCatalogue, cat);

        // Quantity: String -> Integer
        setIfNotNull(vo::setQuantity, parseInteger(src.getQuantity()));

        // Budget (VO has both budgetno & budgetNo)
        setIfNotBlank(vo::setBudgetno, src.getBudgetno());
        setIfNotBlank(vo::setBudgetNo, src.getBudgetno());

        // Price: prefer amount(BigDecimal) else price(double)
        Double price = src.getAmount() != null ? src.getAmount().doubleValue()
                                               : (src.getPrice() != 0.0 ? src.getPrice() : null);
        setIfNotNull(vo::setPrice, price);

        // Dates
        setIfNotNull(vo::setExpiryDate, src.getExpiryDate());
        setIfNotNull(vo::setOrderdate,  src.getOrderdate());

        // People / misc
        setIfNotBlank(vo::setOrderedby, src.getOrderedby());
        setIfNotBlank(vo::setConcentration, src.getConcentration());
        setIfNotBlank(vo::setRemarks, src.getRemarks());
        setIfNotBlank(vo::setCasNumber, src.getCasnumber());

        // Company/material/qty fields (name differences)
        setIfNotBlank(vo::setCompanyinternalno, src.getCompanyInternalNo());
        setIfNotBlank(vo::setSapmaterialno,     src.getSapMaterialNo());
        setIfNotBlank(vo::setWeightvolsubqty,   src.getWvsubqty());

        // Storage & grouping
        setIfNotBlank(vo::setStorageLocation, src.getStorageLocation());
        setIfNotBlank(vo::setGroupName, src.getGroupName());

        // Hazard flags: VO uses String; entity has Boolean
        setIfNotBlank(vo::setHazardousSubstance, boolToString(src.getHazardousSubstance()));
        setIfNotBlank(vo::setCmrSubstance,       boolToString(src.getCmrSubstance()));
        setIfNotBlank(vo::setSkinResorptive,     boolToString(src.getSkinResorptive()));

        // GHS fields (entity stores JSON strings)
        setIfNotNull(vo::setGhsSymbols, parseJsonStringArray(src.getGhsSymbols()));   // -> List<String>
        setIfNotBlank(vo::setGhsCheckbox, flattenJsonStringArray(src.getGhsSignalWord())); // comma-joined

        // H/P phrases & substitution
        setIfNotBlank(vo::sethPhrases, src.gethPhrases());
        setIfNotBlank(vo::setpPhrases, src.getpPhrases());
        setIfNotBlank(vo::setSubstitutionCheck, firstNonBlank(src.getSubstitutionCheck(), src.getSubstitutionOption()));

        // Attachment
        if (src.getFileContent() != null && src.getFileContent().length > 0) {
            vo.setAttachment(src.getFileContent());
        }

        // createdAt in VO is String; entity has Date
        setIfNotBlank(vo::setCreatedAt, dateToString(src.getCreatedAt()));

        // Fields not present in entity -> leave as defaults/null (role, approvals, inventoryType, status, etc.)
        // Optionally surface visibility flag:
        // vo.setStatus(src.isVisibleToUsers() ? "VISIBLE" : "HIDDEN");

        return vo;
    }
    
    
    public static ArchiveInventoryVO toVO(ArchiveInventory src) {
        if (src == null) return null;

        ArchiveInventoryVO vo = new ArchiveInventoryVO();

        // IDs
        vo.setArchiveId(src.getArchiveId());
        vo.setProductId(src.getProductId());

        // Field name differences
        vo.setProductName(src.getProductname());
        vo.setCatalogue(src.getCatalogue());
        vo.setCompanyName(src.getCompanyname());

        // Shared fields
        vo.setQuantity(src.getQuantity());
        vo.setGroupName(src.getGroupName());
        vo.setCompanyinternalno(src.getCompanyinternalno());
        vo.setSapmaterialno(src.getSapmaterialno());
        vo.setWeightvolsubqty(src.getWeightvolsubqty());
        vo.setBudgetno(src.getBudgetno());
        vo.setBudgetNo(src.getBudgetno()); // map to both if needed
        vo.setConcentration(src.getConcentration());
        vo.setRemarks(src.getRemarks());
        vo.setPrice(src.getPrice());

        // Dates
        vo.setOrderdate(src.getOrderdate());
        vo.setExpiryDate(src.getExpirydate());

        // People / audit
        vo.setOrderedby(src.getAddedby()); // mapping "addedby" → orderedby
        vo.setCreatedBy(src.getAddedby()); // optional extra mapping


       
        return vo;
    }


    public List<Map<String, Object>> getArchivedItems(User user) {

		/*
		 * if (!"LABMGMT".equalsIgnoreCase(role)) { throw new
		 * RuntimeException("Unauthorized. Only Lab Management can access archive listings."
		 * ); }
		 */
        List<Map<String, Object>> result = new ArrayList<>();

        // --- General Inventory Archive ---
        List<ArchiveInventory> generalList = archiveInventoryRepo.findAll();
        for (ArchiveInventory item : generalList) {
            Map<String, Object> archiveEntry = new HashMap<>();
            archiveEntry.put("archiveId", item.getArchiveId());
            archiveEntry.put("sourceTable", "Inventory");
            
            Map<String, Object> dataMap = new HashMap<>();

            if (item.getProductname() != null) {
                dataMap.put("item_name", item.getProductname());
            }
            if (item.getGroupName() != null) {
                dataMap.put("location", item.getGroupName());
            }
            // add other fields in the same way

            archiveEntry.put("data", dataMap);
            
            
            archiveEntry.put("canDeletePermanently", true); // assume true for now
            result.add(archiveEntry);
        }

        // --- Fine Chemical Archive ---
        List<ArchiveFineChemicalInventory> fineList = archiveFineChemicalRepo.findAll();
        for (ArchiveFineChemicalInventory item : fineList) {
            Map<String, Object> archiveEntry = new HashMap<>();
            archiveEntry.put("archiveId", item.getArchiveId());
            archiveEntry.put("sourceTable", "finechemicalinventory");
            
            Map<String, Object> dataMap = new HashMap<>();

            if (item.getProductname() != null) {
                dataMap.put("product_name", item.getProductname());
            }
            if (item.getCompanyname() != null) {
                dataMap.put("company", item.getCompanyname());
            }
            if (item.getCasnumber() != null) {
                dataMap.put("cas_number", item.getCasnumber());
            }
            if (item.getHazardousSubstance() != null) {
                dataMap.put("hazardous_substance", item.getHazardousSubstance());
            }

            archiveEntry.put("data", dataMap);

            
            
            Map<String, Object> deletedByMap = new HashMap<>();

            if (user.getName() != null) {
                deletedByMap.put("userId", user.getName());
            }
            if (user.getRole() != null) {
                deletedByMap.put("role", user.getRole());
            }

            archiveEntry.put("deletedBy", deletedByMap);

            archiveEntry.put("canDeletePermanently", true);
            result.add(archiveEntry);
        }

        return result;
    }
    
    private void setArchiveVODataFromInventory(ArchiveInventoryVO vo, Inventory inv) {
    	// Direct mappings with name adjustments
        if (inv.getProductId() != null) vo.setProductId(inv.getProductId());
        if (inv.getProductname() != null) vo.setProductName(inv.getProductname());
        if (inv.getCatalogue() != null) vo.setCatalogue(inv.getCatalogue());
        if (inv.getCompanyname() != null) vo.setCompanyName(inv.getCompanyname());
        if (inv.getQuantity() != null) vo.setQuantity(inv.getQuantity());
        if (inv.getBudgetno() != null) vo.setBudgetno(inv.getBudgetno());
        vo.setPrice(inv.getPrice()); // double → Double auto-boxing
        if (inv.getGroupName() != null) vo.setGroupName(inv.getGroupName());
        if (inv.getCompanyinternalno() != null) vo.setCompanyinternalno(inv.getCompanyinternalno());
        if (inv.getSapmaterialno() != null) vo.setSapmaterialno(inv.getSapmaterialno());
        if (inv.getWeightvolsubqty() != null) vo.setWeightvolsubqty(inv.getWeightvolsubqty());
        if (inv.getConcentration() != null) vo.setConcentration(inv.getConcentration());
        if (inv.getRemarks() != null) vo.setRemarks(inv.getRemarks());

        if (inv.getOrderdate() != null) vo.setOrderdate(inv.getOrderdate());
        if (inv.getExpirydate() != null) vo.setExpiryDate(inv.getExpirydate());
        if (inv.getAddedby() != null) vo.setCreatedBy(inv.getAddedby()); // mapping "addedby" → createdBy

        if (inv.getFileName() != null) vo.setCreatedAt(inv.getFileName()); // map if needed differently
        if (inv.getFileType() != null) vo.setUpdatedAt(inv.getFileType()); // adjust mapping rule
      
        vo.setInventoryType("generalInventory");

    }

    private void setArchiveVODataFromInventory(ArchiveInventoryVO vo, FineChemicalInventory src) {
        
        	vo.setInventoryType("fineChemicalInventory");
        	
        	// 1) Straight mappings / name adjustments
            setIfNotNull(vo::setProductId, src.getProductId());
            setIfNotBlank(vo::setProductName, src.getProductname());

            // VO has "catalogue" (typo); source has both "catalogue" and "catalogue"
            String cat = firstNonBlank(src.getCatalogue(), src.getCatalogue());
            setIfNotBlank(vo::setCatalogue, cat);

            setIfNotBlank(vo::setCompanyName, src.getCompanyname());

            // quantity: source String -> VO Integer
            setIfNotNull(vo::setQuantity, parseInteger(src.getQuantity()));

            // budgetno (lower) is present in both; VO also has budgetNo (camel). Set both to be safe.
            setIfNotBlank(vo::setBudgetno, src.getBudgetno());
            setIfNotBlank(vo::setBudgetNo, src.getBudgetno());

            // price: prefer amount(BigDecimal), else price(double)
            Double price = src.getAmount() != null ? src.getAmount().doubleValue()
                                                   : (src.getPrice() != 0.0 ? src.getPrice() : null);
            setIfNotNull(vo::setPrice, price);

            // Dates
            setIfNotNull(vo::setExpiryDate, src.getExpiryDate());
            setIfNotNull(vo::setOrderdate,  src.getOrderdate());

            // People / strings
            setIfNotBlank(vo::setOrderedby, src.getOrderedby());
            setIfNotBlank(vo::setConcentration, src.getConcentration());
            setIfNotBlank(vo::setRemarks, src.getRemarks());
            setIfNotBlank(vo::setCasNumber, src.getCasnumber());

            // Hazard flags: VO expects String; source has Boolean
            setIfNotBlank(vo::setHazardousSubstance, boolToString(src.getHazardousSubstance()));
            setIfNotBlank(vo::setCmrSubstance,       boolToString(src.getCmrSubstance()));
            setIfNotBlank(vo::setSkinResorptive,     boolToString(src.getSkinResorptive()));

            // Inventory / storage / group
            setIfNotBlank(vo::setStorageLocation, src.getStorageLocation());
            setIfNotBlank(vo::setGroupName, src.getGroupName());
            // VO has inventoryType but FineChemicalInventory doesn’t — leave null unless you have a source.

            // Company / material numbers / qty
            setIfNotBlank(vo::setCompanyinternalno, src.getCompanyInternalNo());
            setIfNotBlank(vo::setSapmaterialno,     src.getSapMaterialNo());
            setIfNotBlank(vo::setWeightvolsubqty,   src.getWvsubqty());

            // GHS fields
            setIfNotNull(vo::setGhsSymbols, parseJsonStringArray(src.getGhsSymbols()));
            // ghsSignalWord in source is a JSON (string). VO has ghsCheckbox (string) but no dedicated field;
            // If you want to surface the signal word, store as ghsCheckbox (or add a field to VO).
            setIfNotBlank(vo::setGhsCheckbox, flattenJsonStringArray(src.getGhsSignalWord()));

            setIfNotBlank(vo::sethPhrases, src.gethPhrases());
            setIfNotBlank(vo::setpPhrases, src.getpPhrases());
            setIfNotBlank(vo::setSubstitutionCheck, firstNonBlank(src.getSubstitutionCheck(), src.getSubstitutionOption()));

            // Attachment
            if (src.getFileContent() != null && src.getFileContent().length > 0) {
                vo.setAttachment(src.getFileContent());
            }

            // Shared/createdAt
            // VO.createdAt is String; map from Date if you want a human-readable timestamp
            setIfNotBlank(vo::setCreatedAt, dateToString(src.getCreatedAt()));
            // Optional: set status defaults, approvals, etc., if desired
            // vo.setStatus("ARCHIVED");
    }
    private static <T> void setIfNotNull(java.util.function.Consumer<T> setter, T value) {
        if (value != null) setter.accept(value);
    }

    private static void setIfNotBlank(java.util.function.Consumer<String> setter, String value) {
        if (value != null && !value.trim().isEmpty()) setter.accept(value.trim());
    }

    private static String firstNonBlank(String a, String b) {
        if (a != null && !a.trim().isEmpty()) return a.trim();
        if (b != null && !b.trim().isEmpty()) return b.trim();
        return null;
    }

    private static Integer parseInteger(String s) {
        if (s == null) return null;
        try { return Integer.valueOf(s.trim()); }
        catch (NumberFormatException e) { return null; }
    }

    private static String boolToString(Boolean b) {
        return b == null ? null : String.valueOf(b); // "true"/"false"
        // Alternatively: return b == null ? null : (b ? "YES" : "NO");
    }

    private static String dateToString(Date d) {
        return d == null ? null : ISO_DATE_TIME.format(d);
    }
    private static final SimpleDateFormat ISO_DATE_TIME = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    /**
     * Parse a JSON array string like ["GHS01","GHS02"] into List<String>.
     * If Jackson is available, prefer that. Fallback is a very simple parser.
     */
    private static List<String> parseJsonStringArray(String json) {
        if (json == null || json.trim().isEmpty()) return null;
        // If Jackson available:
        // try { return MAPPER.readValue(json, new TypeReference<List<String>>(){}); }
        // catch (Exception e) { return null; }

        // Minimal fallback: handles ["a","b"] or comma-separated without quotes.
        String s = json.trim();
        if (s.startsWith("[") && s.endsWith("]")) {
            s = s.substring(1, s.length() - 1).trim();
        }
        if (s.isEmpty()) return Collections.emptyList();
        String[] parts = s.split(",");
        List<String> out = new ArrayList<>(parts.length);
        for (String p : parts) {
            String v = p.trim();
            if (v.startsWith("\"") && v.endsWith("\"") && v.length() >= 2) {
                v = v.substring(1, v.length() - 1);
            }
            if (!v.isEmpty()) out.add(v);
        }
        return out;
    }

    /**
     * Flatten a JSON array string into a comma-separated string for VO.glsCheckbox
     * If already a simple string, returns it as-is.
     */
    private static String flattenJsonStringArray(String json) {
        List<String> list = parseJsonStringArray(json);
        if (list == null) return null;
        return String.join(",", list);
    }
    
}
